# Project information
site_name: Regels
site_author: 'ZuiderVeen'

# Copyright
copyright: Copyright &copy; 2021 ZuiderVeen

# Congiguration
theme:
  name: material
  features:
    # - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: nl
plugins:
  - search:
      lang: nl
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
  - Hoofdpagina: index.md
  - Content: apv.md
  - Crimineel: overvallen.md
  - Hulpdiensten: hulpdiensten.md
  - Iets: index.md
  - NewLifeRule: newliferule.md
  - ValueofLife: valueoflife.md
