# Project information
site_name: Regels
site_author: 'ZuiderVeen'

# Copyright
copyright: Copyright &copy; 2021 ZuiderVeen

# Congiguration
theme:
  name: material
  features:
    # - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: nl
plugins:
  - search:
      lang: nl
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  nav:
  - Hoofdpagina: algemeen.md
  - Kaas1: content-regels.md
  - Kaas2: crimineel.md
  - Kaas3: hulpdiensten.md
  - Kaas4: index.md
  - Kaas5: newliferule.md
  - Kaas6: valueoflife.md

